export const INCREMENT='INCREMENT'
export const SAVEDATA='SAVEDATA'
export const SESSION='SESSION'
export const USER='USER'
export const USERNAME='USERNAME'
export const HEALTH='HEALTH'
export const LIST='LIST'
export const URL='URL'
